services:
  ruby:
    image: ruby:3.2
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: bash
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db 
    command: --default-authentication-plugin=mysql_native_password